### ISSUE TITLE
nx workspace, assets folder is not found

### ISSUE THREAD

**Issue by marcellkiss** [cherryApp/ngc-esbuild#10]
Repo and branch to reproduce:
https://github.com/marcellkiss/angular-web-component-example/tree/feature/ngc-esbuild

I already had this nx workspace repo, so I created a new branch to test the devkit, here's what I have done:
https://github.com/marcellkiss/angular-web-component-example/commit/299dff7a0523420b36ba5aa88490873cf330f9f0
- installed the devkit package
- changed the builder for wp-app

When I'm running the build process `npm run build:wc`, it fails with an error:
ENOENT: no such file or directory, scandir `/Users/user/dev/angular-web-component-example/src/assets`

The proper path would be: `/Users/user/dev/angular-web-component-example/apps/wc-app/src/assets`

wc-app is just one app in the ./apps folder, as I'm in an nx workspace, but the builder handles it as an angular-cli project.

**Comment by cherryApp** [comment]
Hi @marcellkiss 
0.0.63 version supports the multiple project configuration.
Please check it and send me feedback.
Thanks.

**Comment by cherryApp** [comment]
The solution has been done.

**Comment by marcellkiss** [comment]
ngc-esbuild-devkit needs an update, doesn't it? (v0.40 is still the latest)
