### ISSUE TITLE
Doesn't work with tailwindcss 

### ISSUE THREAD

**Issue by sefatanam** [cherryApp/ngc-esbuild#16]
I start with a blank app then I installed tailwindcss when I run my app with `ngc-esbuild --serve --open` It doesn't show any tailwindcss styles but angular material.

**Comment by cherryApp** [comment]
Hi @sefatanam,
I labeled this issue as a feature request.
I like TailwindCSS, but I didn't check the possibility of using it.
Can you send a sample starter application for Angular + Tailwind for me?

**Comment by sefatanam** [comment]
Hi @cherryApp,
I am so much glad to you for taking this issue as a feature request. 💖
I made a starter application with tailwindcss & ngc-esbuild, you can check it out [https://github.com/sefatanam/esbuild-tailwind](https://github.com/sefatanam/esbuild-tailwind) here.

thanks & regards

**Comment by sefatanam** [comment]
Have any update ? @cherryApp
