### ISSUE TITLE
Does not support TypeScript path mapping

### ISSUE THREAD

**Issue by nicholas-ochoa** [cherryApp/ngc-esbuild#2]
It looks like [TypeScript path mapping](https://www.typescriptlang.org/docs/handbook/module-resolution.html#path-mapping) is not yet supported:

```bash
$ npm run esbuild

> app@4.0.0 esbuild C:\git\app
> ngc-esbuild

✘ [ERROR] Could not resolve "@environment"

    src/main.ts:7:28:
      7 │ import { environment } from '@environment';
        ╵                             ~~~~~~~~~~~~~~

  You can mark the path "@environment" as external to exclude it from the bundle, which will remove
  this error.

✘ [ERROR] Could not resolve "@core/layout/layout.component"

    src/app/app-routing.module.ts:6:32:
      6 │ import { LayoutComponent } from '@core/layout/layout.component';
        ╵                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@core/layout/layout.component" as external to exclude it from the bundle,
  which will remove this error.

✘ [ERROR] Could not resolve "@auth/auth.module"

    src/app/app-routing.module.ts:9:45:
      9 │   { path: 'auth', loadChildren: () => import('@auth/auth.module').then((m) => m.AuthModule) },
        ╵                                              ~~~~~~~~~~~~~~~~~~~

  You can mark the path "@auth/auth.module" as external to exclude it from the bundle, which will
  remove this error. You can also add ".catch()" here to handle this failure at run-time instead of
  bundle-time.
```

This is already pretty awesome for an alpha - not sure if you want issues open for pieces that aren't yet in place, I can close this if so. Really looking forward to seeing this move forward!

**Comment by cherryApp** [comment]
Thanks for your feedback.
I think the problem is about the at @ symbol.
When the package is processing the source code, it is very difficult to change paths.
Please change the path to the none-at version and send me feedback about it.

**Comment by cherryApp** [comment]
Please send me a mapping example from your app.

**Comment by nicholas-ochoa** [comment]
Here is an excerpt from my `tsconfig.json` file. The `@` symbol is just used to make the path aliases stand out in the imports. The paths aliases are all part of the application source and not located in `node_modules`.

```json
    "typeRoots": ["node_modules/@types"],
    "outDir": "./dist/out-tsc",
    "baseUrl": "./client",
    "paths": {
      "@environment": ["environments/index.ts"],
      "@package_json": ["../package.json"],
      "@admin/*": ["app/admin/*"],
      "@auth/*": ["app/auth/*"],
      "@core/*": ["app/core/*"],
      "@dashboard/*": ["app/dashboard/*"],
      "@grid/*": ["app/util/grid/*"],
      "@grid": ["app/util/grid/index.ts"],
      "@home/*": ["app/home/*"],
      "@load/*": ["app/load/*"],
      "@util/*": ["app/util/*"]
    }
```

**Comment by cherryApp** [comment]
I tried it.
Mapping worked well when I set this path object in the tsconfig.json file in the root folder.
For example, the below code is worked fine:
```
"@auth/*": ["src/app/auth/*"],
```
Currently, my package processes only the root tsconfig.json file.

Try this:
- move tsconfig.json file to the root directory
- change the paths to a relative from the root: `src/app/auth/*`

**Comment by nicholas-ochoa** [comment]
Unfortunately due to the complexity of how my app / repo is structured I can't easily move the `tsconfig.json` around. Hopefully this is something can be addressed in the future! :)

**Comment by cherryApp** [comment]
Hi @nicholas-ochoa 
Please try it again with the 0.0.61 version.
I implemented the workspace support and NgcEsbuild reads configuration from the angular.json file.
The app will work well when you place the right config path in angular.json.
