### ISSUE TITLE
can't reference correct image if scss style url is "/assets/path-to-assets.ext"

### ISSUE THREAD

**Issue by nickbanana** [cherryApp/ngc-esbuild#6]
https://github.com/nickbanana/esbuild-image-url

this repo contain a minimal repro example.

``` scss
background: url(/assets/img_test.jpg);
```
in the app.component.scss style file, here I reference the file which I put into assets folder

but at the css resolver part

File: bin\plugin\esbuild-css-resolver.js
```js
  for (let match of matches) {
    if (!/data\:/.test(match[0])) {
      try {
        const sourcePath = path.join(workDir, match[1]);
        const fileName = path.basename(sourcePath);
        const targetPath = path.join(instance.outDir, fileName);
        instance.store.fileCopier(
          sourcePath,
          targetPath,
        );
        content = content.replace(match[1], fileName);
```

/assets/img_test.jpg will be replaced by img_test.jpg, thus unable to reference the actual file

**Comment by cherryApp** [comment]
Hi @nickbanana 
Please recheck this issue with the new 0.0.61 version.

**Comment by nickbanana** [comment]
> Hi @nickbanana Please recheck this issue with the new 0.0.61 version.

@cherryApp looks good to me, the assets display correctly
