### ISSUE TITLE
Support for object based assets configuration

### ISSUE THREAD

**Issue by Plevi1337** [cherryApp/ngc-esbuild#8]
Hey,

I've wanted to try out this tool on one of our older already in production angular frontend and I've run into this issue.

```
[ERROR] [plugin angularAssetsResolver] The "path" argument must be of type string. Received an instance of Object

    <project-path>\node_modules\ngc-esbuild\bin\plugin\esbuild-assets-resolver.js:14:42:
      14 │         options.assets.map( asset => path.join(instance.workDir, asset) ),
         ╵                                           ^

    at new NodeError (node:internal/errors:371:5)
    at validateString (node:internal/validators:119:11)
    at Object.join (node:path:429:7)
    at <project-path>\node_modules\ngc-esbuild\bin\plugin\esbuild-assets-resolver.js:14:43
    at Array.map (<anonymous>)
    at setup (<project-path>\node_modules\ngc-esbuild\bin\plugin\esbuild-assets-resolver.js:14:24)
    at async handlePlugins (<project-path>\node_modules\ngc-esbuild\node_modules\esbuild\lib\main.js:856:11)
```

I believe the root cause of the problem is that angular.json supports specifying the assets as objects with glob patterns and input/output mappings like this (snippet is from the official [documentation):](https://angular.io/guide/workspace-config#asset-config)
```
"assets": [
  {
    "glob": "**/*",
    "input": "src/assets/",
    "output": "/assets/"
  },
  {
    "glob": "favicon.ico",
    "input": "src/",
    "output": "/"
  }
]
```

Thank you for reading this, awesome project!

**Comment by cherryApp** [comment]
Hi @Plevi1337 
Please give me a real example of this configuration.
I don't know if this global pattern is supported or not (officially)?
Anyway, I announced the 0.0.61 version, which supports multi workspaces and reads assets paths from the angular.json file.

**Comment by Plevi1337** [comment]
Hi @cherryApp ,

I've created a minimal app to reproduce the issue here: https://stackblitz.com/edit/angular-webcontainer-template-x8lxs6?file=angular.json

The assets config in the angular.json looks like this: 
```json
"assets": [
              {
                "glob": "**/*assets.html",
                "input": "src/assets/",
                "output": "/assets/"
              },
              {
                "glob": "**/*assets2.html",
                "input": "src/assets/",
                "output": "/assets2/"
              }
],
```

There are two files in the src/assets folder:
- outputs_to_assets.html
- outputs_to_assets2.html

If you run an "ng build" you can see that, they are mapped to two different folders in the dist folder respecting the assets config.
- /dist/assets/outputs_to_assets.html
- /dist/assets2/outputs_to_assets2.html

I don't really know a valid use case for this, but it's supported by the angular compiler (see the example and the [documentation](https://angular.io/guide/workspace-config#asset-config)) and for some reason we've configured a few projects this way at my company.

I've installed ngc-esbuild to the example as well. If you run the npm run esbuild command, it will fail with error I've already provided. 
The problem is that in the [esbuild-assets-resolver.js](https://github.com/cherryApp/ngc-esbuild/blob/58037cee7e1067219b89dbb4d635e35908519fd3/bin/plugin/esbuild-assets-resolver.js) on line 14, you treat all members of the options.assets array as string and pass it directly to the path.join function, although it can be an object with a type like this:
```typescript
{ 
    input: string,
    output: string,
    glob: string,
}
```

Thank you very much for taking the time to check this out, I hope my example is clear.

**Comment by peterbanfi** [comment]
> I don't really know a valid use case for this, but it's supported by the angular compiler (see the example and the [documentation](https://angular.io/guide/workspace-config#asset-config)) and for some reason we've configured a few projects this way at my company.

I have the same issue with my Angular 13/ Ionic 6 app, and more complex company apps (Angular 13 as well). Not sure if its helps or not but here you go:

``` json
            "assets": [
              {
                "glob": "**/*",
                "input": "src/assets",
                "output": "assets"
              },
              {
                "glob": "**/*.svg",
                "input": "node_modules/ionicons/dist/ionicons/svg",
                "output": "./svg"
              },
              "src/manifest.webmanifest",
              "src/firebase-messaging-sw.js"
            ],
```

Anyway, cool project Jozsi!

**Comment by cherryApp** [comment]
Hi @Plevi1337 @peterbanfi 
0.0.63 fixed this issue, please check it.
This version supports object-based assets and plain string assets too.

**Comment by Plevi1337** [comment]
Hey, @cherryApp 
It seems to work for me. Thank you very much. Cool project, I'm very much looking forward to using this.
